### ISSUE TITLE
Descarga automatica de video

### ISSUE THREAD

**Issue by fnandoth** [notKimu/Mad-Vods#1]
Basicamente al entrar en la pagina(index) se descarga automaticamente un video y al entrar en un vod se descarga otra vez el mismo video

![image](https://github.com/notKimu/Mad-Vods/assets/62623196/18a03ed0-8907-4faa-ad54-371690c351b6)

**Comment by notKimu** [comment]
Parece que es un problema con la forma que tuve que encontrar de usar el iframe ya que el que da Google Drive da error con el CORS y este es un enlace directo al archivo y puede hacer que algunos navegadores lo descarguen automáticamente, ya he preguntado a los de Drive y ando mirando alguna otra forma de arreglarlo.

**Comment by notKimu** [comment]
Desde el commit https://github.com/notKimu/Mad-Vods/commit/6c3a13d30496e30dff4356e593b7788e7e87a61b estoy usando vídeos de YouTube y los próximos vídeos de Google Drive solo te llevarán al archivo en sí así que problema resuelto owo

**Comment by fnandoth** [comment]
nice uwu.
pero sigues utilizando iframe verdad?

**Comment by notKimu** [comment]
Sip pero el enlace (si es de Google Drive) ahora te lleva a una preview en vez de un link de descarga, por lo que no debería haber problema.
